image:
  file: webapp/.gitpod.Dockerfile
  context: ./webapp

tasks:
  - name: Restore & Build
    init: docker build -t aspnetintro-image -f webapp/.gitpod.Dockerfile webapp/.
    command: docker run -p 3012:3012 aspnetintro-image

ports:
  - port: 3012
    onOpen: open-preview

