image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      docker build -t aspnetcore_intro -f  webapp/Dockerfile webapp/.
    command: |
      docker run -p 3012:3012 aspnetcore_intro

ports:
  - port: 3012
    onOpen: open-preview

vscode:
  extensions:
    - muhammad-sammy.csharp
