image:
  file: webapp/.gitpod.Dockerfile
  context: ./webapp

tasks:
  - name: Restore & Build
    init: |
      docker run -p 3012:3012 aspnetintro-image

vscode:
  extensions:
    - muhammad-sammy.csharp
