
image:
  file: webapp/.gitpod.Dockerfile
  context: ./webapp

tasks:
  - name: Restore & Build
    init: |
      dotnet DotNetIntro.Docker.dll

ports:
  - port: 3012
    onOpen: open-preview


vscode:
  extensions:
    - muhammad-sammy.csharp