
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet restore
      dotnet build
      
  - name: Run
    command: |
      dotnet run

ports:
  - port: 3012
    visibility: public
    onOpen: open-browser

vscode:
  extensions:
    - muhammad-sammy.csharp
