
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      docker build -t aspnetcore_intro -f  webapp/Dockerfile webapp/.
# I can't run the app on prebuild, because gitpod does not understand that the job finished
# It keeps waiting for the jobs to finish, but the run command keeps listening on the port
  - name: Run
    command: |
      docker run -p 3012:3012 aspnetcore_intro

ports:
  - port: 3012
    visibility: public
    onOpen: open-preview

vscode:
  extensions:
    - muhammad-sammy.csharp
    - jsw.csharpextensions
